# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: identity.cnrm.cloud.google.com/v1alpha2
kind: IdentityNamespace
metadata:
  name: default
  namespace: "PROJECT_ID" # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.core.project"}}}
spec: {}
---
apiVersion: container.cnrm.cloud.google.com/v1alpha2
kind: ContainerCluster
metadata:
  clusterName: "PROJECT_ID/us-central1-c/asm-cluster" # {"type":"string","x-kustomize":{"partialSetters":[{"name":"gcloud.core.project","value":"PROJECT_ID"},{"name":"cluster-name","value":"asm-cluster"},{"name":"gcloud.compute.zone","value":"us-central1-c"}]}}
  name: asm-cluster # {"type":"string","x-kustomize":{"setter":{"name":"cluster-name","value":"asm-cluster"}}}
  namespace: "PROJECT_ID" # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.core.project"}}}
spec:
  location: us-central1-c # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.compute.zone"}}}
  releaseChannel:
    channel: REGULAR
  workloadIdentity:
    identityNamespace: default
  labels:
    mesh_id: "CLUSTER_MESH_ID" # {"type":"string","x-kustomize":{"partialSetters":[{"name":"anthos.cluster.mesh_id","value":"CLUSTER_MESH_ID"}]}}
    created-for-anthos-sample-deployment: "RELEASE_DATE" # {"type":"string","x-kustomize":{"partialSetters":[{"name":"anthos.sample.deployment.release_date","value":"RELEASE_DATE"}]}}
  loggingService: logging.googleapis.com/kubernetes
  monitoringService: monitoring.googleapis.com/kubernetes
  addonsConfig:
    horizontalPodAutoscaling:
      disabled: false
    httpLoadBalancing:
      disabled: false
    cloudrunConfig:
      disabled: true
  ipAllocationPolicy:
    useIpAliases: true
  masterAuth:
    username: admin
  network: default  # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.compute.network"}}}
  subnetwork: default # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.compute.subnetwork"}}}
  releaseChannel:
    channel: REGULAR # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.container.cluster.releaseChannel"}}}
  privateClusterConfig:
    enablePrivateEndpoint: true
    enablePrivateNodes: true
    masterIpv4CidrBlock: 172.16.0.0/28 # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.container.cluster.masterIpv4CidrBlock"}}}
  masterAuthorizedNetworksConfig:
    enabled: true
